//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRShared.Source.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRShared.Source.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting internal testing.
        /// </summary>
        internal static string Text_Shared_Begin_Internal_Tests {
            get {
                return ResourceManager.GetString("Text_Shared_Begin_Internal_Tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Group Or Name.
        /// </summary>
        internal static string Text_Shared_Command_Help_Param_CommandGroupOrName {
            get {
                return ResourceManager.GetString("Text_Shared_Command_Help_Param_CommandGroupOrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crash.
        /// </summary>
        internal static string Text_Shared_Command_Name_Crash {
            get {
                return ResourceManager.GetString("Text_Shared_Command_Name_Crash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string Text_Shared_Command_Name_Help {
            get {
                return ResourceManager.GetString("Text_Shared_Command_Name_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setloglevel.
        /// </summary>
        internal static string Text_Shared_Command_Name_SetLogLevel {
            get {
                return ResourceManager.GetString("Text_Shared_Command_Name_SetLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging level.
        /// </summary>
        internal static string Text_Shared_Command_SetLogLevel_Param_Level {
            get {
                return ResourceManager.GetString("Text_Shared_Command_SetLogLevel_Param_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browse.
        /// </summary>
        internal static string Text_Shared_CommandGroup_Browse {
            get {
                return ResourceManager.GetString("Text_Shared_CommandGroup_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chat.
        /// </summary>
        internal static string Text_Shared_CommandGroup_Chat {
            get {
                return ResourceManager.GetString("Text_Shared_CommandGroup_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debug.
        /// </summary>
        internal static string Text_Shared_CommandGroup_Debug {
            get {
                return ResourceManager.GetString("Text_Shared_CommandGroup_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lobby.
        /// </summary>
        internal static string Text_Shared_CommandGroup_Lobby {
            get {
                return ResourceManager.GetString("Text_Shared_CommandGroup_Lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string Text_Shared_CommandGroup_Logging {
            get {
                return ResourceManager.GetString("Text_Shared_CommandGroup_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to match.
        /// </summary>
        internal static string Text_Shared_CommandGroup_Match {
            get {
                return ResourceManager.GetString("Text_Shared_CommandGroup_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matchui.
        /// </summary>
        internal static string Text_Shared_CommandGroup_MatchUI {
            get {
                return ResourceManager.GetString("Text_Shared_CommandGroup_MatchUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to network.
        /// </summary>
        internal static string Text_Shared_CommandGroup_Network {
            get {
                return ResourceManager.GetString("Text_Shared_CommandGroup_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processcontrol.
        /// </summary>
        internal static string Text_Shared_CommandGroup_ProcessControl {
            get {
                return ResourceManager.GetString("Text_Shared_CommandGroup_ProcessControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quickmatch.
        /// </summary>
        internal static string Text_Shared_CommandGroup_Quickmatch {
            get {
                return ResourceManager.GetString("Text_Shared_CommandGroup_Quickmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to social.
        /// </summary>
        internal static string Text_Shared_CommandGroup_Social {
            get {
                return ResourceManager.GetString("Text_Shared_CommandGroup_Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        internal static string Text_Shared_CommandGroup_Test {
            get {
                return ResourceManager.GetString("Text_Shared_CommandGroup_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal testing completed successfully.
        /// </summary>
        internal static string Text_Shared_End_Internal_Tests {
            get {
                return ResourceManager.GetString("Text_Shared_End_Internal_Tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get help for a specific command, use\n\t/help [command]\n\nTo get help for a group of commands, use\n\t/help [command group name]\n\nAvailable command groups:\n\n\t{0} .
        /// </summary>
        internal static string Text_Shared_Help {
            get {
                return ResourceManager.GetString("Text_Shared_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command group or name: &apos;{0}&apos;\n\n{1}.
        /// </summary>
        internal static string Text_Shared_Help_Bad_Input {
            get {
                return ResourceManager.GetString("Text_Shared_Help_Bad_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causes the process to crash immediately..
        /// </summary>
        internal static string Text_Shared_Help_Command_Crash {
            get {
                return ResourceManager.GetString("Text_Shared_Help_Command_Crash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives information about a command or a group of commands..
        /// </summary>
        internal static string Text_Shared_Help_Command_Help {
            get {
                return ResourceManager.GetString("Text_Shared_Help_Command_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the current logging level of this process.
        /// </summary>
        internal static string Text_Shared_Help_Command_SetLogLevel {
            get {
                return ResourceManager.GetString("Text_Shared_Help_Command_SetLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands in this group allow you to browse through the set of open lobbies..
        /// </summary>
        internal static string Text_Shared_Help_CommandGroup_Browse {
            get {
                return ResourceManager.GetString("Text_Shared_Help_CommandGroup_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands in this group help you communicate with other players..
        /// </summary>
        internal static string Text_Shared_Help_CommandGroup_Chat {
            get {
                return ResourceManager.GetString("Text_Shared_Help_CommandGroup_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n\nAdditional help available for commands:\n\n\t{0}.
        /// </summary>
        internal static string Text_Shared_Help_CommandGroup_Commands {
            get {
                return ResourceManager.GetString("Text_Shared_Help_CommandGroup_Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands in this group are used for debugging..
        /// </summary>
        internal static string Text_Shared_Help_CommandGroup_Debug {
            get {
                return ResourceManager.GetString("Text_Shared_Help_CommandGroup_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands in this group are operations for creating, joining, and finding lobbies, as well as manipulating their state..
        /// </summary>
        internal static string Text_Shared_Help_CommandGroup_Lobby {
            get {
                return ResourceManager.GetString("Text_Shared_Help_CommandGroup_Lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands in this group allow you to adjust the logging properties of the process..
        /// </summary>
        internal static string Text_Shared_Help_CommandGroup_Logging {
            get {
                return ResourceManager.GetString("Text_Shared_Help_CommandGroup_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands in this group allow you to perform game operations..
        /// </summary>
        internal static string Text_Shared_Help_CommandGroup_Match {
            get {
                return ResourceManager.GetString("Text_Shared_Help_CommandGroup_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands in this group perform game play actions through the client UI thread..
        /// </summary>
        internal static string Text_Shared_Help_CommandGroup_MatchUI {
            get {
                return ResourceManager.GetString("Text_Shared_Help_CommandGroup_MatchUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands in this group control the client connection to the server..
        /// </summary>
        internal static string Text_Shared_Help_CommandGroup_Network {
            get {
                return ResourceManager.GetString("Text_Shared_Help_CommandGroup_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands in this group allow you to control the execution flow of the process..
        /// </summary>
        internal static string Text_Shared_Help_CommandGroup_ProcessControl {
            get {
                return ResourceManager.GetString("Text_Shared_Help_CommandGroup_ProcessControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands in this group enable players to quickly create games without going through the lobby process..
        /// </summary>
        internal static string Text_Shared_Help_CommandGroup_Quickmatch {
            get {
                return ResourceManager.GetString("Text_Shared_Help_CommandGroup_Quickmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands in this group help you interact with other players..
        /// </summary>
        internal static string Text_Shared_Help_CommandGroup_Social {
            get {
                return ResourceManager.GetString("Text_Shared_Help_CommandGroup_Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands in this group are used to test things.  Most commands will have no help or documentation..
        /// </summary>
        internal static string Text_Shared_Help_CommandGroup_Test {
            get {
                return ResourceManager.GetString("Text_Shared_Help_CommandGroup_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, no help is available for this command.  *sadface*.
        /// </summary>
        internal static string Text_Shared_Help_No_Help_For_Command {
            get {
                return ResourceManager.GetString("Text_Shared_Help_No_Help_For_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (optional).
        /// </summary>
        internal static string Text_Shared_Help_Optional {
            get {
                return ResourceManager.GetString("Text_Shared_Help_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Usage: /{0}.
        /// </summary>
        internal static string Text_Shared_Help_Usage_Command {
            get {
                return ResourceManager.GetString("Text_Shared_Help_Usage_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword ({0}) matches multiple commands..
        /// </summary>
        internal static string Text_Shared_Multiple_Commands_Matched {
            get {
                return ResourceManager.GetString("Text_Shared_Multiple_Commands_Matched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter..
        /// </summary>
        internal static string Text_Shared_Slash_Command_Missing_Parameter {
            get {
                return ResourceManager.GetString("Text_Shared_Slash_Command_Missing_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse value ({0}) for parameter ({1}) at index {2} of type ({3}) on command ({4}).
        /// </summary>
        internal static string Text_Shared_Unable_To_Parse_Parameter {
            get {
                return ResourceManager.GetString("Text_Shared_Unable_To_Parse_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse slash command..
        /// </summary>
        internal static string Text_Shared_Unable_To_Parse_Slash_Command {
            get {
                return ResourceManager.GetString("Text_Shared_Unable_To_Parse_Slash_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undocumented parameter.
        /// </summary>
        internal static string Text_Shared_Undocumented_Parameter {
            get {
                return ResourceManager.GetString("Text_Shared_Undocumented_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command: {0}.
        /// </summary>
        internal static string Text_Shared_Unknown_Command {
            get {
                return ResourceManager.GetString("Text_Shared_Unknown_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Unknown Player&apos;({0}).
        /// </summary>
        internal static string Text_Shared_Unknown_Player {
            get {
                return ResourceManager.GetString("Text_Shared_Unknown_Player", resourceCulture);
            }
        }
    }
}
